name: build-publish-deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2. Setup .NET 8
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      #    # 3. Install dependencies
      #    - name: Install zip
      #      run: sudo apt-get update && sudo apt-get install -y zip
      
      # 4. Restore + Publish
      - name: Publish
        run: |
          dotnet publish PhotoShare.csproj -c Release -o . /p:RestoreLockedMode=true
      
      # 5. Compress artefact
      - name: Compress to zip
        run: zip -r photoshare.zip .
      
      # 6. Clean old artefact
      - name: Remove old directory contents on VM
        continue-on-error: true
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            rm -fr "${{ secrets.VM_PATH }}/*"
      
      # 7. Copy artefact to VM
      - name: Upload to VM
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "photoshare.zip"
          target: "${{ secrets.VM_PATH }}"
      
      # 8. Remote deploy script
      - name: Run deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            /home/deploy/deploy.sh /opt/photoshare/photoshare.zip