name: build-publish-deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Compress source code
      - name: Zip source code
        run: |
          zip -r photoshare.zip . -x ".*"

      # 3. Remove old directory contents on VM
      - name: Clean VM target directory
        continue-on-error: true
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo rm -rf "${{ secrets.VM_PATH }}/*"

      # 4. Upload source to VM
      - name: Upload source to VM
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "photoshare.zip"
          target: "${{ secrets.VM_PATH }}"

      # 5. SSH and run build+deploy
      - name: Run build and deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd "${{ secrets.VM_PATH }}"
            unzip -o "photoshare.zip" -d .
            sudo /usr/local/bin/deploy_photoshare.sh .
            