name: build-publish-deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2. Setup .NET 8
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # 3. Restore + Publish
      - name: Publish
        run: |
          dotnet publish PhotoShare.csproj -r linux-x64 --self-contained true -c Release -o . /p:RestoreLockedMode=true
      
      # 4. Compress artefact
      - name: Compress to zip
        run: zip -r photoshare.zip .
      
      # 5. Clean old artefact
      - name: Remove old directory contents on VM
        continue-on-error: true
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            /usr/bin/rm -fr "${{ secrets.VM_PATH }}/*"
      
      # 6. Copy artefact to VM
      - name: Upload to VM
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "photoshare.zip"
          target: "${{ secrets.VM_PATH }}"
      
      # 7. Remote deploy script
      - name: Run deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_SSH_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            /usr/bin/sudo /usr/local/bin/deploy_photoshare.sh /opt/photoshare/photoshare.zip